[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "3JrVs4qisvju5p7qwY3wahS7MesuArN1cD7N7GYjfY6R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/anchor.ts"
client = "npx tsx client/*.ts"

[toolchain]
anchor_version = "0.32.1"
